-- OCORRENCIA MAIS PRÓXIMAS AO USUÁRIO (NÃO FAZ PARTE DAS 7)

SELECT O.DESCRICAO, O.DATA_E_HORA, O.LATITUDE, O.LONGITUDE, O.TIPO, CDLL(O.LATITUDE, O.LONGITUDE, <LATITUDE_PESSOA>, <LONGITUDE_PESSOA>) AS DISTANCIA
FROM  OCORRENCIA O
ORDER BY DISTANCIA;

-- 23) Organizadores e seus ventos com uma nota superior que a média (TESTAR PARA VERIFICAR MELHOR QUANDO A BASE ESTIVER MAIOR)

SELECT P.NOME AS ORGANIZADOR, O.NOTA AS NOTA_ORGANIZADOR, E.NOME AS EVENTO, E.NOTA AS NOTA_EVENTO, E.DATA_E_HORA, E.LATITUDE, E.LONGITUDE
FROM PESSOA P JOIN ORGANIZADOR O ON P.CPF = O.CPF AND O.NOTA > (SELECT AVG(O.NOTA) FROM ORGANIZADOR O) 
JOIN EVENTO E ON  O.CPF = E.ORGANIZADOR AND E.NOTA > (SELECT AVG(E.NOTA) FROM EVENTO E)
ORDER BY O.NOTA, E.NOTA;

-- TODOS OS AMIGOS QUE ELE TEM EM COMUM COM OUTRO USUÁRIO

SELECT P.NOME, P.CPF
FROM PESSOA P
WHERE EXISTS
    ((SELECT S.SEGUIDOR FROM SEGUIDOR S WHERE S.SEGUIDO = '56153503650' AND P.CPF = S.SEGUIDOR)
    INTERSECT
    (SELECT S.SEGUIDOR FROM  SEGUIDOR S WHERE S.SEGUIDO = '89200907806' AND P.CPF = S.SEGUIDOR)
    )
ORDER BY P.NOME;


-- TODOS OS USUÁRIOS QUE TEM EXATAMENTE OS MESMO AMIGOS QUE VC




-- SELECIONAR TODOS OS SEUS SEGUIDORES QUE PARTICIPAM DE UM DETERMINADO EVENTO

SELECT P.NOME
FROM PESSOA P JOIN SEGUIDOR S
ON S.SEGUIDO = '89200907806' AND P.CPF = S.SEGUIDOR
JOIN PARTICIPANTE PA
ON PA.PESSOA = S.SEGUIDOR AND PA.EVENTO = 0
ORDER BY PA.EVENTO;


-- SELECIONAR QUANTOS SEGUIDORES VÃO NOS MESMOS EVENTOS QUE DETERMINADO USUÁRIO

SELECT E.NOME, E.DATA_E_HORA, COUNT(PA.EVENTO)
FROM PESSOA P JOIN SEGUIDOR S
ON S.SEGUIDO = '89200907806' AND P.CPF = S.SEGUIDOR
RIGHT JOIN PARTICIPANTE PA
ON PA.PESSOA = S.SEGUIDOR
JOIN EVENTO E
ON E.ID = PA.EVENTO
GROUP BY PA.EVENTO, E.NOME, E.DATA_E_HORA
ORDER BY PA.EVENTO;



-- SELECIONAR QUANTOS DE SEUS SEGUIDORES PARTICIPAM DE UM DETERMINADO EVENTO

SELECT E.NOME, COUNT(*) AS NUMERO_DE_SEGUIDORES
FROM SEGUIDOR S
INNER JOIN PARTICIPANTES PA
ON PA.PESSOA = S.SEGUIDOR
INNER JOIN Eventos E
ON PE.EVENTO = E.ID 
WHERE S.SEGUIDO = VOCE
GROUP BY E.ID; 

-- Pegar todas informacoes de uma determinada ocorrencia (SERÁ UTILIZADO CRIMINAL)



-- PESSOAS QUE CRIARAM ALGUMA OCORRENCIA EM DETERMINADO EVENTO